services:
  backend:
    build: backend/.
    ports:
    - "8000:8000"
    expose:
    - "8000"
  frontend:
    build: frontend/.
    ports:
    - "9000:9000"
    expose:
    - "9000"
networks:
  host:
    name: host
    external: true
